### ISSUE TITLE
Unsopported major.minor version 52.0 error

### ISSUE THREAD

**Issue by pankhgupta** [alexfu/androidautoversion#1]
Hi,
I have added dependencies and updated the gradle file as mentioned. 
I am using jdk7, but getting:
Error:Cause: com/github/alexfu/AndroidAutoVersionPlugin : Unsupported major.minor version 52.0

**Comment by freddong** [comment]
I have solved this problem by upgrading gradle from 2.2 to 2.11 and set JAVA_HOME to jdk8.

**Comment by ericwjr** [comment]
I'm having the same issue.

**Comment by alexfu** [comment]
Hey guys, I've pushed a new release with this fix in it. Can you guys update the plugin to `com.github.alexfu:androidautoversion:0.1.3` and confirm that it's working with Java 7?
