### ISSUE TITLE
About the releases

### ISSUE THREAD

**Issue by sudipidus** [alexfu/androidautoversion#10]
should we mentions releaseMajor, releaseMinor, releasePatch as product flavors in gradle file. I followed the wiki, added product flavors, What else should I do?

**Comment by alexfu** [comment]
`releaseMajor`, `releaseMinor`, and `releasePatch` are gradle **_tasks_**. You don't add them to anything. Once you've followed all the steps in the `README`, run one of the 3 gradle tasks above (i.e. `./gradlew releasePatch`).
