### ISSUE TITLE
Gradle sync failed: Task with name 'assembleRelease' not found in project ':app'.

### ISSUE THREAD

**Issue by dsdebastiani** [alexfu/androidautoversion#11]
The error reported in #5 still occurs in Android Auto Version `0.2.1` with Gradle plugin `2.2.1`

I'm only trying  build app to run in device `Shift+F10`. The BuildVariants is setted to `debug` because the app is in development yet.

But if I change the `releaseTask` to `assembleDebug` in config the build runs normally:

```
androidAutoVersion {
    releaseTask "assembleDebug"
    versionFile file("${project.rootDir}/version")
}
```

**Comment by alexfu** [comment]
Weird that this happens in the IDE but not from command line. Looking into it.

**Comment by alexfu** [comment]
@dsdebastiani released a new version with this fix.
