### ISSUE TITLE
Not compatible with Gradle 4.6

### ISSUE THREAD

**Issue by h1st0ry3D** [alexfu/androidautoversion#32]
When using this Plugin with Android Studio 3.2 and Gradle 4.6 I got the error: 

versionName cannot be set on a mergedFlavor directly.
versionNameOverride can instead be set for variant outputs using the following syntax:
android {
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.versionNameOverride = "0.5.3"
        }
    }
}

To fix this, the versionCode and versionName need to be set differently in the method applyVersion(DefaultDomainObjectSet<BaseVariant> variants) of the AndroidAutoVersionPlugin.groovy file.

private applyVersion(DefaultDomainObjectSet<BaseVariant> variants) {
        variants.all { variant ->
             int versionCode = version.versionCode
             String versionName = version.versionName
 
            - variant.mergedFlavor.versionCode = versionCode
            - variant.mergedFlavor.versionName = versionName

             variant.outputs.all { output ->
                + output.versionNameOverride = versionName
                + output.versionCodeOverride = versionCode

**Comment by alexfu** [comment]
@breaxta if you would like to open a PR for this, I'd be happy to review it.

**Comment by rion18** [comment]
Is there a new release for this so we don't have to use 'com.github.alexfu:androidautoversion:8350d23' :)

**Comment by alexfu** [comment]
@rion18 I just published a 3.0.0 you can use that has this fix. Here's the changelog: https://github.com/alexfu/androidautoversion/blob/master/CHANGELOG.md
