### ISSUE TITLE
public static final int VERSION_CODE = -1;

### ISSUE THREAD

**Issue by narlei** [alexfu/androidautoversion#35]
After update to the last version: ` 'com.github.alexfu:androidautoversion:3.0.0'` the VERSION_CODE generated is `-1`: 

`public static final int VERSION_CODE = -1;`

Gradle tools: `'com.android.tools.build:gradle:3.2.1'`
Gradle: `https\:services.gradle.org/distributions/gradle-4.6-all.zip`

**Comment by alexfu** [comment]
@narlei This should be fixed in 3.0.1. Also, the README was updated to include a new instructions: https://github.com/alexfu/androidautoversion/commit/3529812c5e8579a8db8b220cf3a11e7bac87296c#diff-04c6e90faac2675aa89e2176d2eec7d8
