### ISSUE TITLE
Can we have an option only bump the build number?

### ISSUE THREAD

**Issue by Jintin** [alexfu/androidautoversion#42]

**Comment by alexfu** [comment]
What's the use case?

**Comment by Jintin** [comment]
Google play only require unique build number, and we have several track to test or collection feedback before release.
For example if we submit 1.2.3(100) to google play internal/alpha/beta track and found issue or want to modify something, we can submit 1.2.3(101) since it's not really release.

**Comment by alexfu** [comment]
Available in 3.3.0
